Instalamos librerías para interactuar con una base de datos PostgreSQL

In [ ]:
!pip install pandas
!pip install psycopg2
!pip install sqlalchemy

Found existing installation: pandas 2.2.3
Uninstalling pandas-2.2.3:
  Successfully uninstalled pandas-2.2.3

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\commands\uninstall.py", line 102, in run
    uninstall_pathset.commit()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 420, in commit
    self._moved_paths.commit()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 273, in commit
    save_dir.cleanup()
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 124, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 758, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 621, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 619, in _rmtree_unsafe
    os.unlink(fullname)
    ^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\e.rangel\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~andas.libs\\msvcp140-0f2ea95580b32bcfc81c235d5751ce78.dll'

Collecting pandas==2.2.2
  Using cached pandas-2.2.2-cp311-cp311-win_amd64.whl (11.6 MB)
Collecting sqlalchemy==2.0.29
  Downloading SQLAlchemy-2.0.29-cp311-cp311-win_amd64.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 9.5 MB/s eta 0:00:00
Requirement already satisfied: psycopg2-binary in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (2.9.11)
Requirement already satisfied: tzdata>=2022.7 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.2.2) (1.26.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy==2.0.29) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy==2.0.29) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\e.rangel\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Installing collected packages: sqlalchemy, pandas
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.48
    Uninstalling SQLAlchemy-2.0.48:
      Successfully uninstalled SQLAlchemy-2.0.48

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\e.rangel\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~qlalchemy\\cyextension\\collections.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\e.rangel\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip' command.

Una vez instaladas, las importamos

In [9]:
import pandas as pd
from sqlalchemy import create_engine

TypeError: <class 'sqlalchemy.engine.result.Result'> is not a generic class

In [3]:
data = {
    'ID':[1, 2, 3],
    'nombre':['danny','carlos','tyrone'],
    'edad':[31,25,8]
}
df = pd.DataFrame(data)
df

   ID  nombre  edad
0   1   danny    31
1   2  carlos    25
2   3  tyrone     8

Establecemos una conexión con nuestra base de datos creada.

In [4]:
host = '34.122.233.40'
port = 5432
database = 'mi_bd_prueba'
user = 'dyanez'
password = '1234'

engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')

Creamos una tabla con la data anteriormente establecida

In [7]:
table_name = 'mi_tabla'
df.to_sql(table_name, engine, index=False, if_exists='replace')

3

Consultamos la tabla creada

In [8]:
consulta_sql = f"SELECT * FROM {table_name}"
df = pd.read_sql(consulta_sql, engine)
df

   ID  nombre  edad
0   1   danny    31
1   2  carlos    25
2   3  tyrone     8

Insertamos más data (desde csv)

In [9]:
!pip install Faker

Collecting Faker
  Downloading Faker-28.4.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Downloading Faker-28.4.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 18.9 MB/s eta 0:00:00
Installing collected packages: Faker
Successfully installed Faker-28.4.1

In [10]:
from faker import Faker
import random
import csv

rows = []
fake = Faker()
quantity = 2500
for _ in range(quantity):
    id = _ + 1
    nombre = fake.vin()
    cuenta = fake.credit_card_number()
    descripcion = fake.text(max_nb_chars=50)
    categoria = fake.random_element(elements=('Electronics', 'Clothing', 'Home', 'Beauty', 'Toys'))
    stock = random.randint(1,500)
    rows.append([id,nombre,cuenta,descripcion,categoria,stock])

In [11]:
with open('dim_productos.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['id',
                     'nombre',
                     'cuenta',
                     'descripcion',
                     'categoria',
                     'stock'])
    writer.writerows(rows)

In [12]:
df_csv = pd.read_csv('dim_productos.csv')
df_csv

,id,nombre,cuenta,descripcion,categoria,stock
0,1,SF42ZRFE965U4VCHX,6598974045114999,Dog beat bed site why among building.,Clothing,198
1,2,185G3HW19LAHN06GM,4759354579325,Card push art.,Beauty,10
2,3,1NBK0SDD4XCTA2KS0,375744652932070,Participant at civil machine me.,Beauty,120
3,4,NRE2PU9C4EC5VE5Z9,4381687111263293008,Season half analysis. Compare make edge forget.,Clothing,8
4,5,4HC7P9H05YUWHV1BK,3578088570708702,Watch up beyond central.,Clothing,400
...,...,...,...,...,...,...
2495,2496,54S0N8UE4CN08WR7H,3527576535896994,Design rise still else minute beautiful.,Beauty,126
2496,2497,MSHJL2P70GHZT8NG8,3588608897798496,Sell partner ever new choice red style.,Beauty,278
2497,2498,1T56EUD09BR9K6JPW,6011380662139088,Cause member fine ready land company experience.,Home,374
2498,2499,3K68B5HM6PUCYPML9,3549431915607773,Wait happy amount bad.,Clothing,71
2499,2500,VTGNFC8F34UNTXKX5,4109928388732210,Girl defense pass fire worker human generation.,Beauty,182

In [13]:
df_csv.to_sql('dim_productos', engine, index=False, if_exists='replace')

500

In [16]:
consulta_sql = f"SELECT * FROM dim_productos where stock < 5"
df = pd.read_sql(consulta_sql, engine)
df

,id,nombre,cuenta,descripcion,categoria,stock
0,168,AHTYG1KM2ZLLYGE1J,4329712387470954,Quality life reach question lot let white.,Toys,1
1,287,9LLTH50A9ETWC13NC,30268744409217,Control school share important success analysis.,Electronics,2
2,351,K3FJ4K5S0BEWLKDKL,2675583986163702,Product include town idea put evening recognize.,Home,3
3,440,9KEHHCYSXNUT1ZLND,4000770764589156,Million report its and which budget.,Home,3
4,480,SMZCVBP24T2Z2XCA2,4751908362342005,Possible assume soldier local wife.,Electronics,3
5,498,UZ5LN9WP7VDGKRFWM,5445769952566059,Relationship collection onto.,Clothing,2
6,547,06JBWXBA34MSG55CH,213149734839341,Onto then green appear billion.,Electronics,3
7,571,G69EAYJP06NCJDCNL,3516116150873714,History test long establish eight head but.,Toys,4
8,588,6ZTU49M48D0581D0J,3598353496361697,National land west act individual.,Clothing,4
9,696,FC1Z3JX1XU3J3G5B1,2257796713061157,Crime majority laugh.,Clothing,3
10,808,XHHBYN306XG5305MU,3514453635019544,Degree important newspaper tend.,Clothing,3
11,1127,2ARC72H18FAP31LD3,4008673960465506,City sell thousand middle throughout finally.,Toys,4
12,1156,A5778VZ60SNDAJMX3,4512192026524,Direction house red education growth.,Toys,2
13,1419,B56BTEUG7Z8JZ6X41,3511675689257900,Mind not political hear. Democrat against we low.,Home,2
14,1828,N6TX28NLXELKXV4DE,2291618675833969,Century common set training.,Toys,3
15,2159,LN02EGZP2DJ99GAEZ,4816738223870384932,Remember food process tend at value time.,Clothing,3
16,2229,NXN5WN0V9FRPH6740,3529756627857330,Charge agreement account play person hand.,Toys,2
17,2232,66MDBZ6E1ZZGKLGVK,2234344144108657,Ago rich else growth among.,Electronics,3
18,2237,DA8JHRZA2BDVXXPJB,4536164146229652,Their attack still available not less above.,Electronics,4
19,2291,TX5C2G1N30E0GZ77A,4439309779938,Two blood to whether. Second forget hundred west.,Electronics,1